"""Baseline IT Manager schema.

Revision ID: 0001_baseline
Revises:
"""

from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


TABLES = [
    "role_permissions",
    "users",
    "product_models",
    "inventory",
    "licenses",
    "stock_movements",
    "maintenance_records",
    "purchase_request_items",
    "knowledge_articles",
    "assignment_history",
    "scrap_records",
    "audit_logs",
    "stock_items",
    "purchase_requests",
    "roles",
    "permissions",
    "personnel",
    "factories",
    "departments",
    "product_types",
    "brands",
    "license_names",
]


def upgrade():
    op.execute(
        """
        CREATE TABLE roles (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(80) NOT NULL UNIQUE,
            description VARCHAR(255),
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE permissions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            key VARCHAR(120) NOT NULL UNIQUE,
            name VARCHAR(160) NOT NULL,
            description VARCHAR(255),
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE factories (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE departments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE personnel (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_no VARCHAR(50) UNIQUE,
            name VARCHAR(160) NOT NULL,
            email VARCHAR(255),
            department_id INTEGER REFERENCES departments(id),
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE product_types (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE brands (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE license_names (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(160) NOT NULL UNIQUE,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE product_models (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(160) NOT NULL,
            brand_id INTEGER NOT NULL REFERENCES brands(id),
            product_type_id INTEGER REFERENCES product_types(id),
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT uq_product_model_brand_name UNIQUE (brand_id, name)
        );
        CREATE TABLE users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(80) NOT NULL UNIQUE,
            email VARCHAR(255) UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            role_id INTEGER REFERENCES roles(id),
            personnel_id INTEGER REFERENCES personnel(id),
            active BOOLEAN NOT NULL DEFAULT TRUE,
            last_login_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE inventory (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inventory_no VARCHAR(80) NOT NULL UNIQUE,
            computer_name VARCHAR(120),
            serial_no VARCHAR(160) UNIQUE,
            machine_no VARCHAR(120),
            ifs_no VARCHAR(120),
            note TEXT,
            status VARCHAR(30) NOT NULL DEFAULT 'active',
            factory_id INTEGER NOT NULL REFERENCES factories(id),
            department_id INTEGER NOT NULL REFERENCES departments(id),
            product_type_id INTEGER NOT NULL REFERENCES product_types(id),
            brand_id INTEGER NOT NULL REFERENCES brands(id),
            model_id INTEGER REFERENCES product_models(id),
            personnel_id INTEGER REFERENCES personnel(id),
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE licenses (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            license_name_id INTEGER NOT NULL REFERENCES license_names(id),
            license_type VARCHAR(30) NOT NULL DEFAULT 'subscription',
            license_key TEXT,
            email VARCHAR(255),
            password TEXT,
            expires_at DATE,
            note TEXT,
            status VARCHAR(30) NOT NULL DEFAULT 'active',
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE stock_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_type_id INTEGER NOT NULL REFERENCES product_types(id),
            brand_id INTEGER NOT NULL REFERENCES brands(id),
            model_id INTEGER REFERENCES product_models(id),
            quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
            unit VARCHAR(30) NOT NULL DEFAULT 'Adet',
            note TEXT,
            status VARCHAR(30) NOT NULL DEFAULT 'available',
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE stock_movements (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            stock_item_id INTEGER NOT NULL REFERENCES stock_items(id),
            movement_type VARCHAR(20) NOT NULL,
            quantity NUMERIC(12,2) NOT NULL,
            unit VARCHAR(30) NOT NULL DEFAULT 'Adet',
            personnel_id INTEGER REFERENCES personnel(id),
            inventory_id INTEGER REFERENCES inventory(id),
            note TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE maintenance_records (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inventory_id INTEGER NOT NULL REFERENCES inventory(id),
            maintenance_type VARCHAR(30) NOT NULL DEFAULT 'internal',
            fault VARCHAR(255) NOT NULL,
            description TEXT,
            service VARCHAR(160),
            technician VARCHAR(160),
            started_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            status VARCHAR(30) NOT NULL DEFAULT 'pending',
            cost NUMERIC(12,2),
            note TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE purchase_requests (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            request_no VARCHAR(50) NOT NULL UNIQUE,
            requester_id INTEGER REFERENCES personnel(id),
            department_id INTEGER REFERENCES departments(id),
            factory_id INTEGER REFERENCES factories(id),
            status VARCHAR(30) NOT NULL DEFAULT 'pending',
            priority VARCHAR(20) NOT NULL DEFAULT 'normal',
            requested_at TIMESTAMPTZ NOT NULL,
            approved_at TIMESTAMPTZ,
            approved_by VARCHAR(160),
            completed_at TIMESTAMPTZ,
            note TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE purchase_request_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            request_id INTEGER NOT NULL REFERENCES purchase_requests(id) ON DELETE CASCADE,
            product_type VARCHAR(120) NOT NULL,
            device_type VARCHAR(120),
            brand VARCHAR(120),
            model VARCHAR(160),
            quantity NUMERIC(12,2) NOT NULL DEFAULT 1,
            unit VARCHAR(30) NOT NULL DEFAULT 'Adet',
            estimated_unit_price NUMERIC(12,2),
            description TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE knowledge_articles (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(240) NOT NULL,
            slug VARCHAR(260) NOT NULL UNIQUE,
            category VARCHAR(120) NOT NULL DEFAULT 'Genel',
            summary VARCHAR(500),
            content TEXT NOT NULL,
            tags VARCHAR(500),
            status VARCHAR(30) NOT NULL DEFAULT 'draft',
            author_id INTEGER REFERENCES personnel(id),
            view_count INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE assignment_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            personnel_id INTEGER NOT NULL REFERENCES personnel(id),
            asset_type VARCHAR(30) NOT NULL,
            asset_id INTEGER NOT NULL,
            action VARCHAR(30) NOT NULL,
            note TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE scrap_records (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_type VARCHAR(30) NOT NULL,
            source_id INTEGER NOT NULL,
            reason VARCHAR(80) NOT NULL,
            note TEXT,
            scrapped_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE audit_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action VARCHAR(80) NOT NULL,
            entity_type VARCHAR(80),
            entity_id INTEGER,
            actor_user_id INTEGER,
            details JSON,
            created_at TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE role_permissions (
            role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
            permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
            PRIMARY KEY (role_id, permission_id)
        );
        """
    )


def downgrade():
    for table in TABLES:
        op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
